### ISSUE TITLE
Comment - Hooks - fastJoin

### ISSUE THREAD

**Issue by Sicria** [feathers-plus/docs.feathers-plus.org#6]
Comment - Hooks - fastJoin

In the first example, where is ``users`` defined?

```
const postResolvers = {
  joins: {
    author: (...args) => async post => post.author = (await users.find({ query: {
      id: post.userId
    } }))[0],
    
    starers: $select => async post => post.starers = await users.find({ query: {
      id: { $in: post.starIds }, $select: $select || ['name']
    } }),
  }
};
```

Seems to be the case throughout the docs for ``fastJoin``. 

Also places where ``fastJoin(postResolvers, context => query)``
Is it safe to assume that it should be ``fastJoin(postResolvers, context => context.params.query || query)``?

**Comment by eddyystop** [comment]
(1) `const users = app.service('/users);`

`users` is a Feathers service. Anything that has `.get()`, `.find()`, etc. after it is likely a service.

Explicit service creation isn't common in examples in either the old (Auk) docs or these new (Buzzard) ones because its generally understood what they are.

Besides, then people would be asking what `app` and `/users1` are. These are explained in the old The Basics docs https://docs.feathersjs.com/guides/step-by-step/readme.html which are still being rewritten for Buzzard.

(2) The `query`  is this object https://feathers-plus.github.io/v1/feathers-hooks-common/guide.html#Shaping-the-Result

So its depends how you decide to pass that to the server. No standards are imposed. `users.find({ query: { author: true }})` does make sense and then `context.params.query` is correct.

**Comment by eddyystop** [comment]
Todo: Add clarifying notes to Guide and API.

**Comment by barata0** [comment]
I agree the doc is not clear about that

And the problem is where to reference app? 

You need to get the context inside the resolver like this

**async (post, context)**

```
const postResolvers = {
  joins: {
    author: (...args) => async (post, context) => post.author = (await context.app.service('/users').find({ query: {
      id: post.userId
    } })).data[0],
    
    starers: $select => async (post, context) => (post.starers = await context.app.service('/users').find({ query: {
      id: { $in: post.starIds }, $select: $select || ['name']
    } })).data,
  }
};
```

And don´t forget to extract the data property from the result to avoid pagination info

**Comment by Sicria** [comment]
@barata0 You can add ``paginate: false`` in your options to allow unlimited number of records.

**Comment by barata0** [comment]
Thanks

but this wasn´t the question here (as I understood).
I just explained where to get the app reference to access the services.

**Comment by 0xception** [comment]
@barata0 Thanks! your post on getting context helped a lot.

**Comment by ksloan** [comment]
How do you get `context` inside the resolvers? Do you have to use fastJoin inside a wrapper-hook?

**Comment by eddyystop** [comment]
In the example above `author: (...args) => async (post, context) =>` the `context` is the hook's context.

**Comment by walkerandco** [comment]
One more thing  that should be  added to this.

If the service endpoint is authenticated (say by `jwt`), then you have to include this in the params. For example:

```
const stackResolvers = {
  joins: {
    author: (...args) => async (stack, context) => stack.author = (await context.app.service('/users').find({ query: { id: post.author }}))[0]
  }
};
```

For the `context` argument to contain `user` in `params`, you have to have called the `authenticate('jwt')` function in a `before` hook. The internal `find` command does not carry over this parameter, so this has to be done manually in the fastJoin resolver.
